# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalid', models.CharField(max_length=80)),
                ('portal', models.SmallIntegerField(choices=[(1, 'MORGS'), (2, 'BBG'), (3, 'MDAPI'), (4, 'MORGQ'), (5, 'CURREX'), (6, 'ALGOX'), (7, '360T')], help_text='Select Portal')),
                ('platform', models.SmallIntegerField(choices=[(1, 'JPMM'), (2, 'MorganDirect'), (3, 'Bloomberg')], help_text='Select Platform')),
                ('settlement_location', models.SmallIntegerField(choices=[(1, 'NYK'), (2, 'LDN'), (3, 'SGP'), (4, 'TYK'), (5, 'BRA'), (6, 'MUB'), (7, 'HGK')], default=1, help_text='Select Settlement Locs')),
                ('disabled', models.BooleanField(default=False, help_text='Default Auto')),
                ('do_not_trade', models.BooleanField(default=False, help_text='Default False')),
                ('max_trade_size', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Description about account')),
                ('pip_slippage', models.CharField(default='0.0', max_length=2)),
                ('worst_allowable_pnl', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('externalid',),
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('settlement_location', models.SmallIntegerField(choices=[(1, 'NYK'), (2, 'LDN'), (3, 'SGP'), (4, 'TYK'), (5, 'BRA'), (6, 'MUB'), (7, 'HGK')], default=1, help_text='Select Settlement Locs')),
                ('disabled', models.BooleanField(default=False, help_text='Default Auto')),
                ('do_not_trade', models.BooleanField(default=False, help_text='Default False')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.SmallIntegerField(choices=[(1, 'MORGS'), (2, 'BBG'), (3, 'MDAPI'), (4, 'MORGQ'), (5, 'CURREX'), (6, 'ALGOX'), (7, '360T')])),
                ('order', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AlgoXTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('markup_mode', models.SmallIntegerField(choices=[(1, 'TRADER'), (2, 'SALES')], help_text='Select Order Type')),
                ('currency_pair', models.SmallIntegerField(choices=[(1, 'USD-INR'), (2, 'INR-AUD'), (3, 'AUD-USD'), (4, 'GBP-USD'), (5, 'SGD-RUB'), (6, 'HKD-USD'), (7, 'CHN-USD')], help_text='Select Currency Pair')),
                ('amount_unit', models.SmallIntegerField(choices=[(1, 'USD'), (2, '*')], help_text='Select Amount Unit')),
                ('from_amount', models.TextField(max_length=10)),
                ('to_amount', models.TextField(max_length=10)),
                ('hidden_mark_up', models.TextField(default='*', max_length=10)),
                ('explicit_mark_up', models.TextField(default='*', max_length=10)),
                ('fixing_info', models.TextField(default='*', max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountGroup')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('universal_customer_number', models.CharField(max_length=12)),
                ('special_party_number', models.CharField(max_length=30)),
                ('netlink_enabled', models.BooleanField(default=False, help_text='Default False')),
                ('pb_acronym', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DisabledCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy', models.SmallIntegerField(choices=[(1, 'USD'), (2, 'INR'), (3, 'AUD'), (4, 'GBP'), (5, 'SGD'), (6, 'HKD'), (7, 'CHN')])),
                ('order', models.PositiveIntegerField()),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountGroup')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SalesTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order_type', models.SmallIntegerField(choices=[(1, 'TRADER'), (2, 'SALES')], help_text='Select Order Type')),
                ('order', models.PositiveIntegerField()),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountGroup')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountGroup'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
